Refactor RunState to have ownership over build vars
concourse/concourse pull request #6082
Opened 2020-09-21 13:29 UTC by aoldershaw

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## What does this PR accomplish?

**Refactor**

Should (hopefully) be a (relatively) pure refactor that makes it easier to support var interpolation throughout the build plan by providing all steps access to the build vars. It also makes it much more feasible to unit test the `across` step, and is a required step for supporting the dynamic `across` step in the future.

p.s. the commit messages outline the motivations further - I recommend reading the PR commit by commit

## Changes proposed by this PR:

* `exec.RunState` holds the build variables, meaning we can dynamically create new local scopes (each `across` branch runs in its own scope for local vars)
* The `DelegateFactories` are constructed at `exec`-time, rather than at `engine/build` time

## Notes to reviewer:

This change flies in the face of #6022 in a few ways (e.g. @vito removed the delegate factory, whereas I repurposed it).

Side note - I ran into the awkwardness of having checks separated from builds here - #6022 is a really awesome change

## Release Note

## Contributor Checklist

- [ ] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [ ] [Signed] all commits
- [ ] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [ ] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

2020-09-29 21:27 UTC, taylorsilva requested changes
Sorry for getting to this so late! You stuck well to keeping it a pure refactor. I only have the one nit about `shadow`, and I realize it was already part of the code. Following the commits was a good suggestion, it made it easy to keep things straight in my head and follow where things were moving to.

2020-10-02 16:00 UTC, vito commented on atc/exec/across_step.go
> +			fmt.Fprintf(stderr, "\x1b[1;33mWARNING: across step shadows local var '%s'\x1b[0m\n", v.Var)
I think `shadows` is appropriate here, assuming it has the same meaning as in Go and other languages (JavaScript?):

```
$ go vet -shadow main.go
main.go:4: declaration of "n" shadows declaration at main.go:2
```

"Shadow" implies that it's only overridden in the nested scope, and outer scope isn't affected. I'm not sure what behavior is currently implemented. If it's not that, and the value gets clobbered, `overrides` might be better.

2020-10-02 16:01 UTC, aoldershaw commented on atc/exec/across_step.go
> +			fmt.Fprintf(stderr, "\x1b[1;33mWARNING: across step shadows local var '%s'\x1b[0m\n", v.Var)
Current behaviour doesn't affect the outer scope, just the nested scope

2020-10-08 18:02 UTC, taylorsilva approved these changes

2020-10-08 18:02 UTC, merged