WIP: no review for now please
concourse/concourse pull request #6186
Opened 2020-10-21 02:26 UTC by evanchaoli

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## What does this PR accomplish?

Bug Fix | Feature | Documentation

closes # .

## Changes proposed by this PR:

## Notes to reviewer:

## Release Note

## Contributor Checklist

- [ ] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [ ] [Signed] all commits
- [ ] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [ ] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

2020-10-28 14:14 UTC, jmccann commented
Just wanted to say this caught my interest when looking from perspective of a cache that can be used across workers as requested in https://github.com/concourse/concourse/issues/1987 😄

2020-11-10 07:34 UTC, evanchaoli commented
@taylorsilva This PR is ready for review. Code cleaned up and tests added.

2020-11-10 15:31 UTC, vito commented
Pretty dang cool! It sounds like so far this is opt-in and you have to make sure all your workers can reach each other?

I wonder if a future iteration could have workers specify their network somehow - maybe just a name to indicate which workers live in the same network. Or maybe this behavior could be tied to pools somehow? 🤔

Anyway this is awesome, thanks for working on it!

2020-11-10 23:06 UTC, taylorsilva requested changes
This works as expected! Ran a simple job with each step running on a different worker. I added a log line in artifact_source so I could confirm that it used the `p2pStreamTo()`.
<img width="345" alt="image" src="https://user-images.githubusercontent.com/4583837/98743030-6a864280-237d-11eb-9e08-1300e06d4e50.png">

I just have one nit about adding the tracing calls since `streamTo` has it. I'd like to keep parity on those functions and will probably help make it easier to get data on how fast p2p streaming is vs through the web node.

My docker-compose file for testing:
```yaml
version: '3'

services:
  db:
    image: postgres:${POSTGRES_TAG:-latest}
    shm_size: 1gb
    ports:
    - 6543:5432
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  web:
    build: .
    image: concourse/concourse:local
    volumes:
    - .:/src
    command: web
    depends_on: [db]
    ports:
    - 8080:8080
    environment:
      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: dev
      CONCOURSE_POSTGRES_PASSWORD: dev
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test,guest:guest
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_CLUSTER_NAME: dev
      CONCOURSE_ENABLE_PIPELINE_INSTANCES: "true"
      CONCOURSE_ENABLE_ACROSS_STEP: "true"

  worker-1:
    build: .
    image: concourse/concourse:local
    command: worker
    privileged: true
    depends_on: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_TSA_HOST: web:2222

      # avoid using loopbacks
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay

      # so we can reach Garden/Baggageclaim for debugging
      CONCOURSE_BIND_IP: 0.0.0.0
      CONCOURSE_BAGGAGECLAIM_BIND_IP: 0.0.0.0
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "true"
      CONCOURSE_TAG: worker-1
      CONCOURSE_ENABLE_P2P_VOLUME_STREAMING: "true"

  worker-2:
    build: .
    image: concourse/concourse:local
    command: worker
    privileged: true
    depends_on: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_TSA_HOST: web:2222

      # avoid using loopbacks
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay

      # so we can reach Garden/Baggageclaim for debugging
      CONCOURSE_BIND_IP: 0.0.0.0
      CONCOURSE_BAGGAGECLAIM_BIND_IP: 0.0.0.0
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "true"
      CONCOURSE_TAG: worker-2
      CONCOURSE_ENABLE_P2P_VOLUME_STREAMING: "true"
```

2020-11-11 00:30 UTC, evanchaoli commented
> Pretty dang cool! It sounds like so far this is opt-in and you have to make sure all your workers can reach each other?
> 

In our deployments, all workers can reach each other, so I'll immediately enable this feature once it's available.

I have no idea with other deployments, so that I make this feature opt-in. If a cluster administrator knows that all workers can reach each other, then s/he can turn on this feature; otherwise this feature is by default off, innocent by doing nothing.

> I wonder if a future iteration could have workers specify their network somehow - maybe just a name to indicate which workers live in the same network. Or maybe this behavior could be tied to pools somehow? 🤔

I have added two worker CLI options in baggage-claim https://github.com/concourse/baggageclaim/blob/v1.9.0/baggageclaimcmd/command.go#L29-L30, which allows to specify which network interface to use for p2p streaming, and IPv4 or v6 to use, which has been good enough for our deployments.

If some other deployments' network configuration is more complicated, we may enhance later. Or the user may contribute an enhancement. As the core function is there, such enhancement about configuration should be easy to do.

Tied to work pools? Could be a future option. But it's not a priority for our deployments for now.

2020-11-11 08:55 UTC, evanchaoli commented on atc/worker/artifact_source.go
> +	ch := make(chan error, 1)
Added the tracing.

2020-11-11 08:57 UTC, evanchaoli commented
@taylorsilva I have added the tracing. Please hold on merge this PR for a few days even if you have no more comments. Let me run more tests locally, especially for rainy day cases, like source/target workers crashed during streaming. I'll let you know once my tests are done.

2020-11-11 14:50 UTC, aoldershaw commented
> I wonder if a future iteration could have workers specify their network somehow - maybe just a name to indicate which workers live in the same network. Or maybe this behavior could be tied to pools somehow? 🤔

It doesn't need to block this PR, but I think having some notion of separate networks would be useful. I may be wrong, but I suspect we won't be able to enable this on either CI or hush-house because of our physical Darwin/Windows workers + team-specific external workers in hush-house, despite the fact that the vast majority of the workloads run on workers in the same network

Obviously there's no harm in not enabling it, but I'm excited to see the performance gains!

2020-11-12 05:48 UTC, evanchaoli commented
@taylorsilva @vito I have finished my tests. Yesterday I encountered a problem where builds hang up if p2p stream timed out. I tried to debug the issue, and found it hang up in `retryhttp` module:

```
goroutine 38229 [select]:
github.com/cenkalti/backoff.RetryNotify(0xc000b8ca30, 0x42e77e0, 0xc001941200, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:60 +0x32c
github.com/cenkalti/backoff.Retry(0xc0011d0a30, 0x42e77e0, 0xc001941200, 0x0, 0x0)
	/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24 +0x50
github.com/concourse/retryhttp.(*RetryRoundTripper).RoundTrip(0xc000fb64c0, 0xc0018b5c00, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/concourse/retryhttp@v1.0.2/retry_round_tripper.go:55 +0x2a6
```

The I found that @vito seems to hit same problem and created a new version `retryhttp` v1.1.0. After bumping to v1.1.0, http timeout works properly now. So I added a new commit to bump `retryhttp` to v1.1.0.

2020-11-12 19:14 UTC, taylorsilva reviewed
This looks good to me! Holding off on approval until @evanchaoli is done with his testing.

2020-11-12 19:26 UTC, taylorsilva approved these changes

2020-11-12 19:36 UTC, merged