add saml docker-compose  override
concourse/concourse pull request #6262
Opened 2020-11-11 21:59 UTC by chenbh

Simple SAML docker-compose to keep us sane

2020-11-11 22:03 UTC, chenbh commented
Going to mark this as draft while we try to get some more auth connectors docker-compose'd

2020-11-27 19:15 UTC, chenbh commented
@taylorsilva this is now ready for review

2020-12-01 17:29 UTC, taylorsilva requested changes
Everything worked perfectly! One nit

2020-12-01 17:29 UTC, taylorsilva commented on hack/overrides/oidc.yml
> +      CONCOURSE_OIDC_ISSUER: http://oidc:9000
A little bump in the dev experience here but not much we can do about it :(
Can we add a comment to the top explaining that when logging in with this override file they'll be directed to `http://oidc:9000` and they'll need to replace `oidc` with `localhost` to continue logging in. I can see someone that doesn't used docker often being confused by the behaviour

2020-12-02 19:36 UTC, chenbh commented
Updated the comment, and also made the `./hack/dc` script not docker-compose up **EVERYTHING**

2020-12-03 14:59 UTC, taylorsilva approved these changes
lgtm

2020-12-03 19:57 UTC, merged