atc(fix): fix an authorization bug, when a user has multiple roles in a team, then it may randomly hit "forbidden" error.
concourse/concourse pull request #6368
Opened 2020-12-16 06:19 UTC by evanchaoli

## What does this PR accomplish?

Bug Fix 

closes 6367# .

## Changes proposed by this PR:

This is a small logic error in function `hasPermission()`, and fixed the bad logic.

## Release Note

Fix an authorization bug, when a user has multiple roles in a team, then it may randomly hit "forbidden" error.

## Contributor Checklist

- [ ] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [ ] [Signed] all commits
- [ ] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [ ] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

2020-12-16 14:36 UTC, muntac requested changes
@evanchaoli looks good! I suggested two name changes that may make things easier to read.

2020-12-16 14:36 UTC, muntac commented on atc/api/accessor/accessor.go
> +func (a *access) hasPermissionCheckingRole(role string) bool {
```suggestion
func (a *access) hasRequiredRole(role string) bool {
```

2020-12-16 14:36 UTC, muntac commented on atc/api/accessor/accessor.go
> +	has := false
```suggestion
	allow := false
```

2020-12-16 15:43 UTC, evanchaoli commented on atc/api/accessor/accessor.go
> +	has := false
Renamed.

2020-12-16 15:43 UTC, evanchaoli commented on atc/api/accessor/accessor.go
> +func (a *access) hasPermissionCheckingRole(role string) bool {
Renamed.

2020-12-16 15:45 UTC, evanchaoli commented
@muntac Thanks for the suggestion of renaming. Please take a look again.

2020-12-16 16:19 UTC, muntac requested changes
@evanchaoli thanks! I was looking at the other tests and think we can make this test simpler. You could just pass the user and group role, then create the atc.TeamAuth struct in the test function itself.

```
func(requiredRole string, userRole string, groupRole string, expected bool) {
....
fakeTeam1.AuthReturns(atc.TeamAuth{
				userRole: map[string][]string{
					"users": {"some-connector:some-user-id"},
				},
				groupRole: map[string][]string{
				"groups": {"some-connector:some-group"},
				},
			})
...
Entry("user is member and group is viewer attempting owner action", "owner", "member", "viewer", false),
Entry("user is viewer and group is member attempting owner action", "owner", "viewer", "member", false),
....
```

2020-12-17 00:36 UTC, evanchaoli commented
@muntac Revised the tests. Please take a look again.

BTW, #6336 is tiny fix of `fly`, and it could be a candidate for 673 if you ship, could you please review that one also?

2020-12-17 16:21 UTC, muntac approved these changes

2020-12-17 16:22 UTC, merged