Ensure task, set_pipeline, load_var steps have names
concourse/concourse pull request #6410
Opened 2021-01-08 23:24 UTC by taylorsilva

## What does this PR accomplish?
**Bug Fix** | Feature | Documentation

fixes #6405

## Changes proposed by this PR:
These steps should always have names provided. Our docs note that names
are required but our validation doesn't return an error for empty
strings on these steps.

Put and Get steps are safe from this because the validator checks that
their resources exist.

## Release Note

* Return an error when no identifier is provided for task, set_pipeline, and load_var steps

## Contributor Checklist
- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [x] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [x] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

2021-01-11 18:00 UTC, aoldershaw requested changes
What do you think about moving this logic into `ValidateIdentifier` instead? The empty string certainly isn't a valid identifier, after all! Rather than a `*ConfigWarning`, it could return `(*ConfigWarning, error)`.

While this PR will fix the `set_pipeline` step, it doesn't fix e.g. `fly rename-pipeline`, which will let you rename a pipeline to `""`, but does not let you use it. `fly rename-team` fails with an internal server error due to some DB constraint not being met. Addressing the issue at `ValidateIdentifier` will at least force each caller to consider the error case, and will make it easy to migrate the soft identifier validation to strict validation when the time comes

2021-01-12 21:21 UTC, taylorsilva commented
@aoldershaw I thought about that and did wonder "is an empty string an invalid identifier?". I was hesitant to make the change there because I wasn't sure if this was true everywhere. I was worried about increasing the scope of that function. I guess that makes sense though; anywhere we expect an identifier we also expect it to no be an empty string. I'll move the implementation to that function.

2021-01-12 22:44 UTC, taylorsilva commented
@aoldershaw made the changes. Need to add tests for the api layer for the error being returned now still.

2021-01-14 15:21 UTC, aoldershaw requested changes
Some minor changes, but it also [looks like there's a compilation issue](https://ci.concourse-ci.org/builds/67942986#L5ffe96d9:522):

```
fly/commands/set_pipeline.go:43:14: assignment mismatch: 1 variable but atc.ValidateIdentifier returns 2 values
```

2021-01-14 15:21 UTC, aoldershaw commented on atc/api/configserver/save.go
> +		session.Info("ignoring-invalid-config", lager.Data{"error": err.Error()})
Maybe change this log message:

```suggestion
		session.Info("ignoring-invalid-pipeline-name", lager.Data{"error": err.Error()})
```

similarly for the team name

2021-01-14 15:21 UTC, aoldershaw commented on atc/configwarning.go
> +	var err error
Maybe get rid of this var - doesn't look like it's needed (and it's kind of misleading to see `return nil, err` at the end, given that the `err` is `nil`

2021-01-14 15:21 UTC, aoldershaw commented on atc/configwarning.go
>  	if identifier != "" && !validIdentifiers.MatchString(identifier) {
Nit, but you can get rid of the first condition

```suggestion
	if !validIdentifiers.MatchString(identifier) {
```

2021-01-14 15:21 UTC, aoldershaw commented on atc/configwarning.go
> +		return nil, errors.New("identifier cannot be an empty string")
Perhaps this should incorporate the `context` as we do with warnings - that way you won't need all the `fmt.Sprintf("%s: %s", identifier, err.Error())` in `atc/configvalidate/validate.go`

```suggestion
		return nil, fmt.Errorf("%s: identifier cannot be an empty string", strings.Join(context, ""))
```

2021-01-18 14:47 UTC, aoldershaw requested changes

2021-01-18 14:47 UTC, aoldershaw commented on atc/api/config_test.go
> +										"identifier cannot be an empty string"
There seems to be a few failing tests now as a result of adding the context to the error: https://ci.concourse-ci.org/builds/69020323#L60011778:17:83

(just requires changing the asserted error message)

2021-01-19 15:11 UTC, aoldershaw approved these changes

2021-01-19 15:27 UTC, merged