Bump dex to 0.4.0 and remove pkger
concourse/concourse pull request #6669
Opened 2021-03-16 19:40 UTC by aoldershaw

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## What does this PR accomplish?

Bug Fix | Feature | Documentation

closes #6563 .

## Changes proposed by this PR:

* Bump dex to 0.4.0, which includes the new dexidp/dex release 2.28.0
  * We have a PR for including an http filesystem which previously used pkger to bundle the assets, but now uses Go 1.16's file embedding
  * There were also some changes to the template - now, assets are referenced using a relative path, so we don't need to specify the paths relative to `/sky/issuer`

## Notes to reviewer:

`go mod tidy` picked up a bunch of other dependency updates as well, so we just left them in

## Release Note

## Contributor Checklist

- [ ] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [ ] [Signed] all commits
- [ ] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [ ] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

2021-03-17 19:17 UTC, chenbh requested changes

2021-03-17 19:17 UTC, chenbh commented on go.mod
> +	github.com/opencontainers/runtime-spec v1.0.3-0.20200929063507-e6143ca7d51d
Actually it looks like gomod resorts to this format when a repo doesn't follow the gomodules convention, but it's weird how it picked up `v1.0.3` (all the other ones are `v0.0.0-...`)

I would rollback to `v1.0.2` just for our sanity.

2021-03-17 20:57 UTC, xtremerui commented on go.mod
> +	github.com/containerd/containerd v1.5.0-beta.1
it passes!

2021-03-17 21:03 UTC, xtremerui commented
@chenbh both are reverted

2021-03-18 14:15 UTC, chenbh approved these changes
That last commit is still authored and signed off by `Frances Bar <bar@awesometown.local>`, but otherwise lgtm

2021-03-22 14:42 UTC, merged