containerd: properly populate /etc/hosts and /etc/hostname
concourse/concourse pull request #7041
Opened 2021-05-19 21:27 UTC by muntac

[add yourself]: https://github.com/concourse/governance#individual-contributors
[PR requirements]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md#pull-request-requirements

## Changes proposed by this PR
cc: @chenbh 

closes #6811

* [x] add hostname to `/etc/hostname`
* [x] add container's IP and hostname to `/etc/hosts`

## Notes to reviewer

The container's IP is only available once the network has been initialized. Therefore, the original /etc/hosts has to be updated after. The /etc/hosts on the container is bindmounted to a file on the worker.  We simply update this
file directly.

To test simply jump on to a running container and open the `/etc/hosts` and `/etc/hostname` file. You can also run `hostname -f` and `hostname -i` to validate.

## Release Note

* containerd: `/etc/hosts` and `/etc/hostname` are correctly populated

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

2021-05-21 20:31 UTC, taylorsilva requested changes

2021-05-21 20:31 UTC, taylorsilva commented on worker/runtime/integration/integration_test.go
> +
We don't need to create a custom garden backend if we're not changing anything from the default values. Use `s.gardenBackend` instead.
```suggestion
```

2021-05-21 20:31 UTC, taylorsilva commented on worker/runtime/integration/integration_test.go
> +	container, err := customBackend.Create(garden.ContainerSpec{
```suggestion
	container, err := s.gardenBackend.Create(garden.ContainerSpec{
```

2021-05-21 20:31 UTC, taylorsilva commented on worker/runtime/integration/integration_test.go
> +		customBackend.Stop()
```suggestion
		s.NoError(s.gardenBackend.Destroy(handle))
```

2021-05-21 20:31 UTC, taylorsilva commented on worker/runtime/integration/integration_test.go
> +	fmt.Println(buf.String())
from debugging I'm guessing
```suggestion
```

2021-05-25 16:01 UTC, taylorsilva approved these changes
LGTM

2021-05-25 16:43 UTC, muntac commented
Thanks! Good eye with the test cleanup suggestions.

2021-05-25 16:43 UTC, merged

2021-05-28 19:20 UTC, jaredstehler commented
would it be possible to get this included in the next point release?

2021-06-23 12:49 UTC, steveburton4 commented
@taylorsilva Do you know when this is planned to be released?

2021-06-24 20:19 UTC, taylorsilva commented
Soon maybe? Looking at our milestone: https://github.com/concourse/concourse/milestone/75
It looks like we could probably cut another release soon.

2021-08-19 21:56 UTC, Christian-Oleson commented
@jaredstehler , 
If I am reading this right it looks like this fix went out in the last release:
https://github.com/concourse/concourse/releases/tag/v7.4.0

2021-08-20 06:09 UTC, steveburton4 commented
> @jaredstehler ,
> If I am reading this right it looks like this fix went out in the last release:
> https://github.com/concourse/concourse/releases/tag/v7.4.0

It did. We have installed it already and tested it fixes the issue we were having 👍