Adds remoteAddr IP to audit logs.
concourse/concourse pull request #8375
Opened 2022-05-23 15:24 UTC by riuvshyn

[add yourself]: https://github.com/concourse/governance#individual-contributors
[PR requirements]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md#pull-request-requirements

## Changes proposed by this PR
Having audit logs without address of request origin isn't very helpful for security audit, so having at least remoteAddr would improve situation a lot.

related to: https://github.com/concourse/concourse/issues/6604

Adds remoteAddr IP to audit logs.

## Release Note

* Adds remoteAddr IP to audit logs.

2022-05-23 16:10 UTC, tburko commented
yes please 👍

2022-05-23 21:46 UTC, xtremerui commented
@taylorsilva wondering your opinions here as well in terms of the implementations of using `r.RemoteAddr`. Thx!

2022-05-24 18:58 UTC, taylorsilva requested changes
@riuvshyn Did you see the PR I made previously? https://github.com/concourse/concourse/pull/6462

There are a lot of possible ways to get a users IP. The big case is when there's a loadbalancer and trying to discern if it's passed along a users IP. I'm not seeing anything that would capture a users IP from `X-Forwarded-For` or `X-Request-Id` headers.

There was also discussion of adding a new config option to allow people to set what header logging should look at to grab the users IP. 

I think a good first pass at this problem in general would be to grab the user's IP from:

1. Well known loadbalancer headers `X-Forwarded-For` and `X-Request-Id`
2. From `r.RemoteAddr` if those headers aren't present.

I would consider that enough to close the issue. If operators want the flexibility of defining a custom header, you could add that to the PR now or wait until someone comes back with feedback requesting such a feature.

2022-11-25 22:29 UTC, xtremerui commented
Given this PR's popularity and its use case, I would like to include it in v7.9. @riuvshyn are you able to address the change request?

> * Well known loadbalancer headers `X-Forwarded-For` and `X-Request-Id`
> * From `r.RemoteAddr` if those headers aren't present.

Thank you for the PR anyway.

2023-06-14 17:05 UTC, xtremerui commented
closing due to inactivity.

2023-06-14 17:05 UTC, closed without merging