Allow SSM Parameters to specify a format using tags
concourse/concourse pull request #8425
Opened 2022-06-15 00:37 UTC by ConnorWidtfeldt

## Changes proposed by this PR

Currently, there is no way to access fields from vars sourced via SSM. This is because Concourse has no understanding of the format the parameter value is in. This change allows Concourse to read SSM parameter tags (with ssm:ListTagsForResource) and check for a tag called "format" which will behave the exact same as the load_vars format. Thus allowing JSON and YAML formats to be loaded. 

* [x] implement unmarshalling using a value set in the tags
* [ ] ensure that the same values are returned when the ssm:ListTagsForResource action is not applied.
* [ ] check for any remaining steps I could have missed in this...

## Notes to reviewer

Most of the code is a modified version of the load_vars handler. Maybe these should be moved into a shared location?

## Release Note

Allow SSM Parameters to specify a format using tags

* The AWS SSM credential manager can now load different file formats when a format is specified in a tag on the parameter.

2022-06-15 13:32 UTC, taylorsilva commented
You may not be able to see the logs from the failed tests but they're all under the SSM test suite. You should be able to replicate the failures by running: `go test atc/creds/ssm/`

2022-06-15 14:03 UTC, ConnorWidtfeldt commented
> You may not be able to see the logs from the failed tests but they're all under the SSM test suite. You should be able to replicate the failures by running: `go test atc/creds/ssm/`

Is there anything special I need to do to see the output of the unit tests on ci.concourse-ci.org? I'll run them locally too, but I figured I would check in case it was an easy add.

2022-06-15 15:05 UTC, taylorsilva commented
Add yourself as a contributor in this repo: https://github.com/concourse/governance

2022-06-16 15:08 UTC, taylorsilva commented
The downgrade test is failing. That's in `./integration/ops`.
The integration tests are slower. They bring up concourse locally using docker compose to test stuff at a higher level.

2022-06-16 15:17 UTC, ConnorWidtfeldt commented
I should probably try running all the tests locally to see what's up. I'm surprised to see it run slower, it should only process a parameter if it's not a raw value, which is the only thing I can think of that would cause slowdowns outside of the secondary request to AWS to get the tags (these unit tests have no ways of testing for network latency, right?) 

Glad I started with a simpler PR for my first contribution to Concourse. I'm learning a ton about the setup.

2022-06-22 21:50 UTC, taylorsilva requested changes
Didn't look over tests yet but made some comments for small improvements. Mostly nits to make things more inline with the rest of the code base. This is looking great so far though! 🎉

2022-06-22 21:50 UTC, taylorsilva commented on atc/creds/ssm/ssm.go
> +			}
Once you enter this case you can `break` out of the `for` loop

2022-06-22 21:50 UTC, taylorsilva commented on atc/creds/ssm/ssm.go
> +		value = string(input)
```suggestion
		value = input
```
Redundant type casting

2022-06-22 21:50 UTC, taylorsilva commented on atc/creds/ssm/ssm.go
> +		return nil, fmt.Errorf("unknown format %s, should never happen, ", format)
```suggestion
		return nil, fmt.Errorf("unknown format %w, should never happen, ", format)
```
Use `%w`: https://pkg.go.dev/fmt#Errorf

2022-06-22 22:18 UTC, ConnorWidtfeldt commented on atc/creds/ssm/ssm.go
> +	}
Oh, that looks way better. I like to remove as much nesting as possible, and you make a good point about it correctly handling the error case.

2022-11-19 03:06 UTC, closed without merging