Fly excludes Mac metadata when uploading local inputs
concourse/concourse pull request #8939
Opened 2024-04-05 22:10 UTC by selzoc

## Changes proposed by this PR

On recent MacOS machines, tar files created (i.e. from `fly execute` with a local resource) include files prefixed by `._`. 
 As a result, once you transfer this tar file to a Linux system and untar, these files may interfere with jobs. This flag will prevent that from happening.

closes #8916

## Release Note

* `fly execute` no longer includes mac metadata when uploading local inputs

2024-04-05 22:25 UTC, taylorsilva requested changes
This looks great! Thanks for having the fix in a separate commit to make reviewing easier. I'll figure out this CI and CodeQL stuff.

One thing I'm also not sure about is if our current scripts will run the tests in go-archive or if we'll have to update CI. Going to look into that.

2024-04-05 22:25 UTC, taylorsilva commented on go-archive/NOTICE.md
You can remove this file and the LICENSE.md too, they're both covered by the one's in the root of the Concourse repo. Some owners and license. This one is actually outdated since it still says Pivotal

2024-04-05 22:33 UTC, taylorsilva commented
Looks like all the unit tests should get run: https://github.com/concourse/ci/blob/883ba8faf5db4ae8af582143cd7d54f0a59e958b/tasks/scripts/unit#L26

2024-04-05 22:50 UTC, taylorsilva commented on go-archive/NOTICE.md
Realized I could make this change myself and not bother you with this nit

2024-04-05 22:59 UTC, selzoc commented
> Looks like all the unit tests should get run: https://github.com/concourse/ci/blob/883ba8faf5db4ae8af582143cd7d54f0a59e958b/tasks/scripts/unit#L26

I'll note that the code that is changed in `go-archive` has no unit tests.  We'd probably have to do a little refactor to pass in a CommandRunner or something if we want to verify the flags passed to `tar`.

2024-04-26 22:13 UTC, selzoc commented
@taylorsilva any updates here?  I'm not able to see the concourse output of the failed ci runs.

2024-04-27 01:27 UTC, taylorsilva commented
@selzoc yes! Could you rebase on master please? We had to fix some stuff in the integration test suite. Once you rebase and CI runs again I'll merge the PR. Thanks for pinging btw

2024-04-27 01:27 UTC, taylorsilva approved these changes
Just need CI to pass

2024-04-28 18:15 UTC, taylorsilva commented
Ah there's an issue with `houdini` depending on `go-archive` still:

```
# github.com/concourse/concourse/worker/runtime/integration

../gopath/pkg/mod/github.com/vito/houdini@v1.1.3/container.go:15:2: missing go.sum entry for module providing package github.com/concourse/go-archive/tarfs (imported by github.com/vito/houdini); to add:

	go get github.com/vito/houdini@v1.1.3

FAIL	github.com/concourse/concourse/worker/runtime/integration [setup failed]
```

2024-05-03 17:00 UTC, selzoc commented
OK I pushed a fix for that integration failure - it's a bit weird to have inlined `go-archive` and also indirectly reference it, but 🤷

2024-05-03 23:12 UTC, taylorsilva commented
From the most recent run:
```
There were failures detected in the following suites:

  tarfs ./go-archive/tarfs [Compilation failure]

  tgzfs ./go-archive/tgzfs [Compilation failure]

  zipfs ./go-archive/zipfs [Compilation failure]


Test Suite Failed
```
and above that
```
Failed to compile tarfs:


go: updates to go.mod needed; to update it:

	go mod tidy


Failed to compile tgzfs:


go: updates to go.mod needed; to update it:

	go mod tidy


Failed to compile zipfs:


go: updates to go.mod needed; to update it:

	go mod tidy
```
![image](https://github.com/concourse/concourse/assets/4583837/17beb050-5855-4ff4-982f-96ffb4ce7c73)

2024-06-16 19:20 UTC, taylorsilva commented
So running the `go-archive` tests with `go test` works fine:

<img width="803" alt="image" src="https://github.com/concourse/concourse/assets/4583837/d80a3017-679e-400c-9255-b0627aca6c29">

Running with ginkgo results in the error seen in CI, which runs this command:
```
ginkgo -r -p -flake-attempts=3 -race -skip-package ./integration,testflight,topgun,./worker/runtime/integration,./worker/baggageclaim "$@"
```

Which gets us this output (truncated by me):
```
Output from proc 1:
  flag provided but not defined: -ginkgo.flake-attempts
  Usage of /Users/taylor/workspace/concourse/concourse/go-archive/tarfs/tarfs.test:
<truncated>
```

2024-06-17 01:49 UTC, merged

2024-06-17 01:50 UTC, taylorsilva commented
Thanks for the initial push making this PR happen @selzoc

2024-06-17 02:18 UTC, selzoc commented
Thanks for the follow-through @taylorsilva !