Pipeline identity token var_source
concourse/concourse pull request #9035
Opened 2024-12-03 08:03 UTC by dbaumgarten

## Changes proposed by this PR

This PR showcases how an implementation of https://github.com/concourse/rfcs/pull/139 could look.

The idtoken var_source generates a signed jwt, which contains infomation about the pipeline (team, pipeline-name etc.). It can be send to external services for authentication.

This PR makes it possible to have a pipeline like this:
```
var_sources:
- name: idtoken
  type: idtoken
  config:
    aud: ["sts.amazonaws.com"]
    ttl: 1h

jobs:
- name: print-creds
  plan:
  - task: print
    config:
      platform: linux

      image_resource:
        type: registry-image
        source: {repository: ubuntu}

      run:
        path: bash
        args:
        - -c
        - |
          echo token: ((idtoken:token))
          // Send this token as part of an API-Request to an external service
```

* [x] Added var_source for identity tokens
* [ ] Store and retrieve signing keys in DB
* [ ] Publish signing keys as JWKs

## Notes to reviewer

It is not intended to be merged as it, but should bring the discussion of this topic forward.

2025-04-26 08:55 UTC, dbaumgarten commented
Hey @taylorsilva ,

as of now Phase 1 of the RFC is nearly complete. Tokens can be obtained from the var-source, keys are stored in the DB and published via a public API-Endpoint as JWKs. I tested it with vault's JWT-Auth feature and it is working just fine.

Still missing is the job/step info in the token (honestly, I have no idea how to do this...) and of course tests.

If you have some time to spare, I would appreciate some feedback, so I can see if I am going in the right direction.
(It is however not super urgent, as I am going on vacation for about a week, so take your time :) )

2025-05-15 16:36 UTC, taylorsilva requested changes
I've given the smaller pieces of this a quick glance. It's looking good so far.

I haven't had time to dig into the job/step name stuff yet. Definitely isn't straight forward how we'll get that in there. Not sure if it may bee a good opportunity to use the Options pattern here 🤔 

I see you're adding testflight tests now, really appreciate that!

Don't forget to add tests to the API layer.

Thanks for the work so far, it's looking great! 👏

2025-05-16 06:33 UTC, dbaumgarten commented on atc/db/migration/migrations/1746768931_add_signing_keys.up.sql
> +    created_at timestamp without time zone DEFAULT now() NOT NULL
kid and kty are two fields from the jwk (added as separate colums for easier searchability). Naming these colums differently would make the connection between the colums and the jwk-fields less obvious.

2025-05-16 06:43 UTC, dbaumgarten commented
I tried adding the job-info. But it turned out to be a gigantic mess and in the end didn't even work out properly...

I did find barely any tests in atc/api, so I assumed this isn't the place for tests. But I can add some there.

2025-05-23 15:50 UTC, taylorsilva commented
Awesome! Thanks for all the work. I'm going to start wrapping my head around all the code changes here and reviewing. There is a lot so might take me a bit of time.

2025-05-23 16:04 UTC, dbaumgarten commented
Yeah, this somehow turned out much larger than expected...
Take your time

2025-05-26 15:56 UTC, taylorsilva requested changes
Thanks for waiting. Overall this is looking really good! I haven't had time to test it locally but I'm happy to see you added some tests to `testflight`!

I just unpaused the pipeline for this PR, so we'll see how all those tests go. I'll play around with this soon, just wanted to share the feedback I have so far.

I think the changes you made to get the job name in are good. It does seem like too much work to get the step name in. Like our RFC said, best effort to get it in. I think most folks will be happy having the job name in there. It's probably enough granularity for users to work with.

The majority of my feedback is what I'd consider "nit-pick" level stuff, though they should be easy to resolve.

The one thing I do request be changed is how the `SigningKeyLifecycler` gets wired up and invoked.

Once that's resolved though and I play around with it a bit, I'm not seeing any other blockers with getting this in. Thanks so much for all the work you've done so far!

2025-05-26 16:37 UTC, dbaumgarten commented
That's a lot of (quite reasonable) feedback. I will resolve it step by step, but it might take a few days.

2025-05-26 16:39 UTC, dbaumgarten commented on atc/atccmd/command.go
> +	go signingKeyLifecycler.Run(context.Background())
That does indeed simplify a lot of things. Godd to know something like this exists!

2025-05-26 16:42 UTC, dbaumgarten commented on atc/creds/idtoken/token_generator.go
> +		ID:       generateRandomNumericString(),
This was some kind of "planning ahead" for the originally planned token-introspection endpoint.
But as I am currently doubting that it would bring any measurable benefit (for now) the jti claim can probably be left out.

2025-05-26 16:44 UTC, dbaumgarten commented on atc/creds/secrets_factory.go
> +type SecretLookupContext struct {
Yeah, I also thought the collision with the context package is unfortunate. I just couldn't come up with a fitting collision-free name. Params seem fine.
I guess that means the interface SecretsWithContext should also be renamed accordingly.

2025-05-30 09:31 UTC, dbaumgarten commented on atc/creds/idtoken/manager.go
> +				}
I tried that and it doesn't work. It seems to be neccessary to do the casting in two steps, as the []string-case always fails otherwise.

2025-05-30 10:36 UTC, dbaumgarten commented
Hi @taylorsilva ,
I have adressed your findings. Things look quite a bit cleaner now.

2025-05-30 11:31 UTC, dbaumgarten commented
I would really like to know what checks are failing there and why.
However it seems like I am unable to view the pipelines. Clicking on the failed checks brings me to a concourse, but login in with github then just shows me an empyt and endlessly loading page:
![grafik](https://github.com/user-attachments/assets/e51302fe-1578-4f3c-97df-718e569ad60a)

2025-06-11 15:05 UTC, dbaumgarten commented
@taylorsilva did you already find some time to play around with this feature?

2025-06-11 16:01 UTC, taylorsilva commented
Hey I haven't yet. I've been busy wrangling the pipelines as I update them to produce arm64 artifacts. I'm hoping to have it all wrapped up this week and will get back to reviewing PR's end of this week / next week. That's the reason I haven't circled back to reviewing this PR and others. See the "In Progress" column here: https://github.com/orgs/concourse/projects/54

The arm64 stuff will also make it easier for me to review PR's. Right now I have to boot up a separate machine (amd64) to properly test Concourse. Once the pipelines are producing arm64 I'll be able to develop 100% on my M-series Mac.

2025-06-23 18:37 UTC, taylorsilva commented
FYI: I had to rebase the branch, the goimport command had a small change and some unrelated files needed to be updated, which was done on `master`.

I am actively reviewing this now, thanks for waiting 🙏

2025-06-23 21:26 UTC, taylorsilva requested changes
Almost there, just want your thoughts on the new `instance` scope.

2025-06-23 21:26 UTC, taylorsilva commented on atc/creds/idtoken/token_generator.go
> +		return fmt.Sprintf("%s/%s/%s/%s", team, pipeline, ivars, job)
If the pipeline does not have any instance vars  and you set the scope to `job`, you end up with a subject like `main/test//print-creds`, which feels unexpected.

I see why you built it up this way; increasing granularity with job being the most granular you can get.

The `instance` scope wasn't something brought up or discussed in the RFC. I wonder if we should replicate the format we follow in our URL's, where the instance vars come at the end.


I'm not sure what would make the most sense for end users to want here. I would prefer having the instance vars at the end of the subject:

```
job: main/test/print-creds/hello:world,key:ivar-here
```

And maybe some users would want the job but not the instance vars?
```
job: main/test/print-creds
```

We also already store the instance vars in the `instance_vars` key in the JWT. Maybe we leave instance vars there and don't include them in the subject? I'd assume any tool smart enough to parse a subject WITH instance vars would be smart enough to look the instance vars up in their own key in the JWT, no?

What do you think? I'm curious what you're thoughts are and what you think or know upstream tools that parse the JWT would be able to handle. The `sub` feels a bit unwieldy when it includes instance vars.

2025-06-23 22:33 UTC, dbaumgarten commented on atc/creds/idtoken/token_generator.go
> +		return fmt.Sprintf("%s/%s/%s/%s", team, pipeline, ivars, job)
Some tools are pretty flexible when it comes to handling JWTs. Vault for example can match on arbitrary claims for authorization.

Others however (most notably AWS and Azure) only do exact matches on the sub claim.
In AWS for example you can configure a Role so that the holder of a signed JWT with sub-claim-value "X" may assume/use it to do stuff in AWS with certain permissions.

The challenge for the design of the sub-claim values is now to to it in a way that allows you to cover the most common scenarios by simply matching on the exact value of the sub-claim:

- All pipelines of team foo may use the role -> Match for sub="foo"
- Only pipeline bar (and all of it's instances) may assume the role -> Match for sub="foo/bar"
- Only instance env=prod of pipeline bar may assume the role -> Match for sub="foo/bar/env=prod"
- Only the none-instanced version of pipeline bar may assume the role -> Match for sub="foo/bar/"
- Only job buz of instance env=prod of pipeline bar may assume the role -> Match for sub="foo/bar/env=prod/buz"
- Only job buz of the non-instance of pipeline bar may assume the role -> Match for sub="foo/bar//buz"

Always keeping the instance-segment (even when it is empty) is neccessary to be able to specifiy a sub-value that matches ONLY the non-instanced version of a pipeline.

If we find a suitable placeholder-value we might use it instead of including an empty segment for non-instanced pipelines: ```foo/bar/<no_vars>/buz```. Would that be clearer?

I am strictly for the hierarchical approach team->pipeline->instance->job, because that is how users navigate Concourse's UI. Putting the instance-vars at the end would be confusing.



And alternative way I thought about is, letting the user choose which components to include in the sub-claim. For example: ```subject_parts: ["team", "job"]``` and prefixing the path-elements with what they represent to prevent any confusion ```team:foo/job:buz```.
This would offer the greatest possible flexibility as it allows you to leave out parts from the sub.
You could then support scenarios like:
- All jobs named buz in any pipeline of team foo may use the role -> Match for sub="team:foo/job:buz"

However I came to the conclusion that the added flexibility isn't really worth the additional complexity (and additional length of the sub-claim-value). What do you think?

2025-06-24 15:21 UTC, taylorsilva commented on atc/creds/idtoken/token_generator.go
> +		return fmt.Sprintf("%s/%s/%s/%s", team, pipeline, ivars, job)
> Others however (most notably AWS and Azure) only do exact matches on the sub claim.

Okay, that's the kind of info I was hoping you had and could share. That's a good enough reason for me to agree to keep instance vars in the sub claim.

> However I came to the conclusion that the added flexibility isn't really worth the additional complexity (and additional length of the sub-claim-value). What do you think?

I agree, I'm quite against making the sub claim configuration more flexible.

You've convinced me to keep the PR as-is. I still think `foo/bar//buz` is odd, but the practical reasons you laid out override that concern for me.

2025-06-24 15:21 UTC, taylorsilva approved these changes

2025-06-24 15:21 UTC, merged

2025-06-24 15:24 UTC, taylorsilva commented
@dbaumgarten Thanks again for the work on this PR.

Would you have time to add documentation for it here: https://github.com/concourse/docs/blob/master/lit/docs/vars.lit#L385-L529
Which renders here: https://concourse-ci.org/vars.html#schema.var_source

2025-06-24 15:52 UTC, dbaumgarten commented
You're welcome :)
Glad I could contribute something useful.

I will take a look at the documentation in the next few days.

Do you already have a rough idea when a version containing this feature will be released?

2025-06-24 19:42 UTC, taylorsilva commented
> Do you already have a rough idea when a version containing this feature will be released?

I am planning to make a 7.14 release that would contain this feature. 7.14 will also contain the first official ARM release of Concourse, which is the main reason for the release. I need to finish the release engineering work and then I'll make a release. Some time in July is my current goal.

2025-06-25 14:11 UTC, dbaumgarten commented
@taylorsilva Do you think I should also add a page to the Credential Management Section of the docs, explaining the feature in more detail (maybe including examples)?

Or is the section under var-sources good enough?

2025-06-25 15:11 UTC, taylorsilva commented
> Do you think I should also add a page to the Credential Management Section of the docs, explaining the feature in more detail (maybe including examples)?

I think that's a good idea. It feels a bit odd putting it on that page, but I don't think there's a better place for it right now. Do it!